formatter: markdown

version: ""

header-from: .header.md

recursive:
  enabled: false
  path: modules


content: ""

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    


sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true